### ISSUE TITLE
Make jstoolbox compliant with other packages in M4dNation organization

### ISSUE THREAD

**Issue by axelvaindal** [M4dNation/jstoolbox#4]
## Summary

`jstoolbox` is a very intuitive package we use in almost all of our projects, but it is now a bit old.
We need to clean it to use more of ES6+ functionalities and migrate the test suite to jest for compliance with other projects.

## Objective

- Make `jstoolbox` compliant with the other packages in M4dNation organization

## Related issues

- [ ] [#1](https://github.com/M4dNation/jstoolbox/issues/1)
- [x] [#2](https://github.com/M4dNation/jstoolbox/issues/2)
- [ ] [#3](https://github.com/M4dNation/jstoolbox/issues/3)
